client_secret: SoGQIV7AlnQScVk4TfcJGmNssG9MhBym
debug: false
disable_auto_update: false
disable_command_execute: false
disable_force_update: false
disable_nat: false
disable_send_query: false
gpu: false
insecure_tls: false
ip_report_period: 1800
probe_test_port: 2080
report_delay: 1
self_update_period: 0
server: agent.098712.xyz:8008
skip_connection_count: false
skip_procs_count: false
temperature: false
tls: false
use_gitee_to_upgrade: false
use_ipv6_country_code: false
uuid: ""
